// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(smp_clr,0,0);
        VL_IN8(set_clr,0,0);
        VL_IN8(smp_en,0,0);
        VL_IN8(state,0,0);
        VL_IN8(label,3,0);
        VL_OUT8(predict,3,0);
        CData/*0:0*/ rchdc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__smp_clr;
        CData/*0:0*/ rchdc__DOT__set_clr;
        CData/*0:0*/ rchdc__DOT__smp_en;
        CData/*0:0*/ rchdc__DOT__state;
        CData/*3:0*/ rchdc__DOT__label;
        CData/*3:0*/ rchdc__DOT__predict;
        CData/*3:0*/ rchdc__DOT__smp_cnt;
        CData/*0:0*/ rchdc__DOT__smp_done;
        CData/*0:0*/ rchdc__DOT__set_en;
        CData/*0:0*/ rchdc__DOT__set_done;
        CData/*3:0*/ rchdc__DOT__set_cnt;
        CData/*0:0*/ rchdc__DOT__am_wr;
        CData/*3:0*/ rchdc__DOT__cls_mimi;
        CData/*4:0*/ rchdc__DOT__g_class__BRA__0__KET____DOT__cls_simi;
        CData/*4:0*/ rchdc__DOT__g_class__BRA__1__KET____DOT__cls_simi;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__clear;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__cnt;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__done;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__0__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__1__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__2__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__3__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__4__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__5__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__6__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__7__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__8__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__9__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__10__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__11__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__12__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__13__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__14__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__15__KET____DOT__im_bit_nb;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__elemCnt__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__elemCnt__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__elemCnt__DOT__en;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__elemCnt__DOT__max;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__elemCnt__DOT__cnt;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__elemCnt__DOT__co;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__elemCnt__DOT__cnt_max;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__elemCnt__DOT__cnt_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__rst_n;
    };
    struct {
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__clr;
    };
    struct {
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__clear;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__cnt;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__done;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__0__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__1__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__2__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__3__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__4__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__5__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__6__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__7__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__8__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__9__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__10__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__11__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__12__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__13__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__14__KET____DOT__im_bit_nb;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__15__KET____DOT__im_bit_nb;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__elemCnt__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__elemCnt__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__elemCnt__DOT__en;
    };
    struct {
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__elemCnt__DOT__max;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__elemCnt__DOT__cnt;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__elemCnt__DOT__co;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__elemCnt__DOT__cnt_max;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__elemCnt__DOT__cnt_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__clr;
    };
    struct {
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__clk;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__rst_n;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__clr;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__en;
        CData/*0:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__one_bit;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__acc;
        CData/*3:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__acc_next;
        CData/*0:0*/ rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__clk;
        CData/*4:0*/ rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__simi;
        CData/*0:0*/ rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__ff_simi__DOT__clk;
        CData/*4:0*/ rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__ff_simi__DOT__data;
        CData/*4:0*/ rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__ff_simi__DOT__qout;
        CData/*0:0*/ rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__clk;
        CData/*4:0*/ rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__simi;
        CData/*0:0*/ rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__ff_simi__DOT__clk;
        CData/*4:0*/ rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__ff_simi__DOT__data;
        CData/*4:0*/ rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__ff_simi__DOT__qout;
        CData/*3:0*/ __VdfgRegularize_hd87f99a1_0_0;
    };
    struct {
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(im_value,15,0);
        VL_IN16(im_pos,15,0);
        SData/*15:0*/ rchdc__DOT__im_value;
        SData/*15:0*/ rchdc__DOT__im_pos;
        SData/*15:0*/ rchdc__DOT__smp_enc;
        SData/*15:0*/ rchdc__DOT____Vcellinp__spatio_enc__data;
        SData/*15:0*/ rchdc__DOT__set_enc;
        SData/*15:0*/ rchdc__DOT____Vlvbound_h633f0857__0;
        SData/*15:0*/ rchdc__DOT__spatio_enc__DOT__data;
        SData/*15:0*/ rchdc__DOT__spatio_enc__DOT__enc;
        SData/*15:0*/ rchdc__DOT__tempo_enc__DOT__data;
        SData/*15:0*/ rchdc__DOT__tempo_enc__DOT__enc;
        SData/*15:0*/ rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__a;
        SData/*15:0*/ rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__b;
        SData/*15:0*/ rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__xor_ab;
        SData/*15:0*/ rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__a;
        SData/*15:0*/ rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__b;
        SData/*15:0*/ rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__xor_ab;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<SData/*15:0*/, 10> rchdc__DOT__AM;
        VlUnpacked<CData/*0:0*/, 8> rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__g_adder_stg__BRA__0__KET____DOT__addend1;
        VlUnpacked<CData/*0:0*/, 8> rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__g_adder_stg__BRA__0__KET____DOT__addend2;
        VlUnpacked<CData/*1:0*/, 8> rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__g_adder_stg__BRA__0__KET____DOT__sum_s;
        VlUnpacked<CData/*1:0*/, 4> rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__g_adder_stg__BRA__1__KET____DOT__addend1;
        VlUnpacked<CData/*1:0*/, 4> rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__g_adder_stg__BRA__1__KET____DOT__addend2;
        VlUnpacked<CData/*2:0*/, 4> rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__g_adder_stg__BRA__1__KET____DOT__sum_s;
        VlUnpacked<CData/*2:0*/, 2> rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__g_adder_stg__BRA__2__KET____DOT__addend1;
        VlUnpacked<CData/*2:0*/, 2> rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__g_adder_stg__BRA__2__KET____DOT__addend2;
        VlUnpacked<CData/*3:0*/, 2> rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__g_adder_stg__BRA__2__KET____DOT__sum_s;
        VlUnpacked<CData/*3:0*/, 1> rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__g_adder_stg__BRA__3__KET____DOT__addend1;
        VlUnpacked<CData/*3:0*/, 1> rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__g_adder_stg__BRA__3__KET____DOT__addend2;
        VlUnpacked<CData/*4:0*/, 1> rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__g_adder_stg__BRA__3__KET____DOT__sum_s;
        VlUnpacked<CData/*0:0*/, 8> rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__g_adder_stg__BRA__0__KET____DOT__addend1;
        VlUnpacked<CData/*0:0*/, 8> rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__g_adder_stg__BRA__0__KET____DOT__addend2;
        VlUnpacked<CData/*1:0*/, 8> rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__g_adder_stg__BRA__0__KET____DOT__sum_s;
        VlUnpacked<CData/*1:0*/, 4> rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__g_adder_stg__BRA__1__KET____DOT__addend1;
        VlUnpacked<CData/*1:0*/, 4> rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__g_adder_stg__BRA__1__KET____DOT__addend2;
        VlUnpacked<CData/*2:0*/, 4> rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__g_adder_stg__BRA__1__KET____DOT__sum_s;
        VlUnpacked<CData/*2:0*/, 2> rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__g_adder_stg__BRA__2__KET____DOT__addend1;
        VlUnpacked<CData/*2:0*/, 2> rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__g_adder_stg__BRA__2__KET____DOT__addend2;
        VlUnpacked<CData/*3:0*/, 2> rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__g_adder_stg__BRA__2__KET____DOT__sum_s;
        VlUnpacked<CData/*3:0*/, 1> rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__g_adder_stg__BRA__3__KET____DOT__addend1;
        VlUnpacked<CData/*3:0*/, 1> rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__g_adder_stg__BRA__3__KET____DOT__addend2;
        VlUnpacked<CData/*4:0*/, 1> rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__g_adder_stg__BRA__3__KET____DOT__sum_s;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__CNT_W = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__elemCnt__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__spatio_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__CNT_W = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__elemCnt__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__0__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__1__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__2__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__3__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__4__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__5__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__6__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__7__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__8__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__9__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__10__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__11__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__12__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__13__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__14__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__tempo_enc__DOT__g_sample__BRA__15__KET____DOT__bitAcc__DOT__DW = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__ADDER_LENGTH = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__g_class__BRA__0__KET____DOT__simi__DOT__ff_simi__DOT__DW = 5U;
    static constexpr IData/*31:0*/ rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__ADDER_LENGTH = 4U;
    static constexpr IData/*31:0*/ rchdc__DOT__g_class__BRA__1__KET____DOT__simi__DOT__ff_simi__DOT__DW = 5U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
